#!/bin/sh

$HOME/.config/bspwm/autostart.sh
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

xidlehook  --not-when-audio --not-when-fullscreen --timer 300 "betterlockscreen -l dim --off 5 --time-format %I:%M-%P" - &
xautolock -time 30 -locker "systemctl suspend" -detectsleep &

bspc config border_width         0
bspc config window_gap            8

bspc config top_padding  28
bspc config bottom_padding  3
bspc config left_padding  3
bspc config right_padding 3

bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#89b9f0"
bspc config focused_border_color        "#33ffe1"
bspc config presel_feedback_color       "#5e81ac"
#bspc config urgent_border_color        "#dd2727"




#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a Galculator state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a Yt-dlg state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a Steam state=floating 

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Zathura state=tiled

#open applications on specific workspaces

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a TelegramDesktop  desktop='^5' follow=on
bspc rule -a  Spotify  desktop='^4'  follow=on
bspc rule -a YouTube\Music desktop='^4' follow=on
bspc rule -a BashTOP desktop='^7' follow=on
bspc rule -a Steam desktop='^7' 
